ALTER TABLE user_info MODIFY COLUMN username VARCHAR(32) NOT NULL;
ALTER TABLE order_info MODIFY COLUMN username VARCHAR(32) NOT NULL;
ALTER TABLE nihongo_user_info MODIFY COLUMN username VARCHAR(32) NOT NULL;
ALTER TABLE milktea_user_info MODIFY COLUMN username VARCHAR(32) NOT NULL;
ALTER TABLE milktea_user_info ADD COLUMN dish_count INT UNSIGNED NOT NULL AFTER username;